# RAFTOP CPAP CARE Pro
# Phase 37.4 - Frontend Deployment Guide
# Safe ASCII-only script

$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$ReportsDir = Join-Path $Root "reports"

if (!(Test-Path $ReportsDir)) {
    New-Item -ItemType Directory -Path $ReportsDir | Out-Null
}

$Timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
$ReportPath = Join-Path $ReportsDir ("phase37_frontend_deployment_guide_" + $Timestamp + ".md")
$Now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

function W {
    param([string]$Text)
    Add-Content -Path $ReportPath -Value $Text -Encoding UTF8
}

Set-Content -Path $ReportPath -Value "# RAFTOP CPAP CARE Pro - Phase 37.4 Frontend Deployment Guide" -Encoding UTF8

W ""
W ("Generated: " + $Now)
W ""
W "FINAL STATUS"
W ""
W "FINAL STATUS: PHASE37_FRONTEND_DEPLOYMENT_GUIDE_READY"
W ""
W "------------------------------------------------------------"
W ""
W "PURPOSE"
W ""
W "This guide defines the production frontend deployment plan for RAFTOP CPAP CARE Pro."
W ""
W "The frontend must be deployed only after the production backend URL and production environment policy are clear."
W ""
W "------------------------------------------------------------"
W ""
W "FRONTEND DEPLOYMENT TARGET"
W ""
W "- Platform: Render Static Site, Vercel, Netlify, or similar production frontend hosting"
W "- Application directory: enterprise-frontend"
W "- Build system: React"
W "- Production build command: npm install && npm run build"
W "- Publish directory: build or dist, depending on the frontend toolchain"
W "- API connection: production backend URL only"
W ""
W "------------------------------------------------------------"
W ""
W "CRITICAL RULE"
W ""
W "The production frontend must never point to localhost, demo backend, or stale backend URLs."
W ""
W "The frontend API base URL must point to the production backend service."
W ""
W "Example production API URL:"
W ""
W "https://your-backend.onrender.com"
W ""
W "Not allowed:"
W ""
W "- http://localhost:5001"
W "- http://127.0.0.1:5001"
W "- expired Render backend"
W "- old demo backend"
W "- staging backend used as production"
W ""
W "------------------------------------------------------------"
W ""
W "REQUIRED FRONTEND ENVIRONMENT VARIABLES"
W ""
W "The exact variable name depends on the React setup."
W ""
W "Common CRA pattern:"
W ""
W "REACT_APP_API_BASE_URL=https://your-backend.onrender.com"
W ""
W "Common Vite pattern:"
W ""
W "VITE_API_BASE_URL=https://your-backend.onrender.com"
W ""
W "Only one correct production API base URL should be active."
W ""
W "------------------------------------------------------------"
W ""
W "PRODUCTION BUILD REQUIREMENTS"
W ""
W "- Dependencies install successfully"
W "- Frontend builds without fatal errors"
W "- Production API URL is configured"
W "- No localhost backend reference remains"
W "- No demo-only frontend flags remain enabled"
W "- Patient portal routes are included"
W "- Admin routes are included"
W "- Tenant context UI works"
W "- Auth state persists correctly"
W ""
W "------------------------------------------------------------"
W ""
W "SUGGESTED RENDER STATIC SITE SETTINGS"
W ""
W "- Service type: Static Site"
W "- Root directory: enterprise-frontend"
W "- Build command: npm install && npm run build"
W "- Publish directory for Create React App: build"
W "- Publish directory for Vite: dist"
W "- Environment: production"
W ""
W "If the project uses Create React App, publish directory is usually build."
W "If the project uses Vite, publish directory is usually dist."
W ""
W "------------------------------------------------------------"
W ""
W "FRONTEND DEPLOYMENT STEPS"
W ""
W "1. Confirm latest code is pushed to GitHub."
W "2. Create a new frontend hosting service."
W "3. Set root directory to enterprise-frontend."
W "4. Set build command."
W "5. Set publish directory."
W "6. Add production API base URL environment variable."
W "7. Deploy latest commit."
W "8. Open the deployed frontend URL."
W "9. Run login and route verification."
W ""
W "------------------------------------------------------------"
W ""
W "REQUIRED FRONTEND ROUTE CHECKS"
W ""
W "- Login page loads"
W "- Admin dashboard loads after login"
W "- Tenant context bar loads"
W "- Patients page loads"
W "- Devices page loads"
W "- Compliance page loads"
W "- ATLAS pages load"
W "- Security Command Center loads"
W "- Patient portal login or access flow loads"
W "- Patient dashboard loads"
W "- Patient therapy page loads"
W "- Demo launcher routes do not expose restricted production controls"
W ""
W "------------------------------------------------------------"
W ""
W "ACCEPTABLE RESPONSES"
W ""
W "- Login page renders"
W "- Protected routes redirect unauthenticated users"
W "- Authenticated routes load after login"
W "- Tenant data appears only for the selected tenant"
W "- Patient routes are guarded"
W "- API errors are displayed safely"
W ""
W "------------------------------------------------------------"
W ""
W "NOT ACCEPTABLE RESPONSES"
W ""
W "- Blank white screen"
W "- Cannot GET route errors"
W "- 404 for expected frontend routes"
W "- Mixed content errors"
W "- CORS errors caused by wrong backend origin"
W "- Frontend still calling localhost"
W "- Frontend calling old demo backend"
W "- Patient portal accessible without guard"
W "- Admin routes accessible to patient role"
W ""
W "------------------------------------------------------------"
W ""
W "CORS DEPENDENCY"
W ""
W "The backend CORS_ORIGIN must match the production frontend URL."
W ""
W "Example:"
W ""
W "Frontend URL:"
W "https://raftop-frontend.onrender.com"
W ""
W "Backend CORS_ORIGIN:"
W "https://raftop-frontend.onrender.com"
W ""
W "Wildcard CORS is not acceptable for production."
W ""
W "------------------------------------------------------------"
W ""
W "SECURITY RULES"
W ""
W "- Do not store secrets in frontend code"
W "- Do not expose SUPER_ADMIN_API_KEY"
W "- Do not expose RESTORE_KEY"
W "- Do not expose database credentials"
W "- Do not expose JWT secret"
W "- Do not hardcode production tokens"
W "- Patient portal must remain guarded"
W "- Admin tools must remain role-protected"
W ""
W "------------------------------------------------------------"
W ""
W "COMMON FRONTEND DEPLOYMENT FAILURES"
W ""
W "- Build failed: check dependencies and package.json"
W "- Wrong publish directory: use build for CRA or dist for Vite"
W "- API not working: check API base URL"
W "- CORS blocked: backend CORS_ORIGIN is wrong"
W "- Login fails: backend URL, auth route, or database problem"
W "- Blank screen: check browser console and build output"
W "- Route not found on refresh: hosting rewrite rule may be missing"
W "- Localhost calls in production: environment variable is wrong"
W ""
W "------------------------------------------------------------"
W ""
W "SPA REWRITE RULE"
W ""
W "React single page apps often need a rewrite rule so direct route refresh works."
W ""
W "Required behavior:"
W ""
W "All frontend routes should serve index.html."
W ""
W "Without this, routes may work through navigation but fail on browser refresh."
W ""
W "------------------------------------------------------------"
W ""
W "MINIMUM FRONTEND ACCEPTANCE CHECKLIST"
W ""
W "- Frontend deployed: PENDING"
W "- Production API URL configured: PENDING"
W "- No localhost references: PENDING"
W "- Login page tested: PENDING"
W "- Admin dashboard tested: PENDING"
W "- Tenant context tested: PENDING"
W "- Patients page tested: PENDING"
W "- Devices page tested: PENDING"
W "- ATLAS page tested: PENDING"
W "- Security Command Center tested: PENDING"
W "- Patient portal tested: PENDING"
W "- Route refresh tested: PENDING"
W "- CORS verified: PENDING"
W "- Role guards verified: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "NEXT PHASE"
W ""
W "Phase 37.5 - Production Environment Checklist"
W ""
W "This will consolidate backend env vars, frontend env vars, database URL rules, secrets policy, CORS policy, and deployment validation."
W ""
W "------------------------------------------------------------"
W ""
W "FINAL VERDICT"
W ""
W "RAFTOP CPAP CARE Pro now has a frontend deployment guide."
W ""
W "The frontend must not be treated as production-ready until production API URL, CORS, route refresh, role guards, tenant context, and patient portal access are verified."
W ""
W "FINAL STATUS: PHASE37_FRONTEND_DEPLOYMENT_GUIDE_READY"

Write-Host ""
Write-Host "============================================================"
Write-Host "RAFTOP CPAP CARE Pro - Phase 37.4 Frontend Deployment Guide"
Write-Host "============================================================"
Write-Host ""
Write-Host "Report created:"
Write-Host $ReportPath
Write-Host ""
Write-Host "FINAL STATUS: PHASE37_FRONTEND_DEPLOYMENT_GUIDE_READY"
Write-Host ""