# RAFTOP CPAP CARE Pro
# Phase 38.1 - Production Deployment Execution Pack
# Safe ASCII-only script

$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$ReportsDir = Join-Path $Root "reports"

if (!(Test-Path $ReportsDir)) {
    New-Item -ItemType Directory -Path $ReportsDir | Out-Null
}

$Timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
$ReportPath = Join-Path $ReportsDir ("phase38_production_deployment_execution_pack_" + $Timestamp + ".md")
$Now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

function W {
    param([string]$Text)
    Add-Content -Path $ReportPath -Value $Text -Encoding UTF8
}

Set-Content -Path $ReportPath -Value "# RAFTOP CPAP CARE Pro - Phase 38.1 Production Deployment Execution Pack" -Encoding UTF8

W ""
W ("Generated: " + $Now)
W ""
W "FINAL STATUS"
W ""
W "FINAL STATUS: PHASE38_PRODUCTION_DEPLOYMENT_EXECUTION_PACK_READY"
W ""
W "------------------------------------------------------------"
W ""
W "PURPOSE"
W ""
W "This execution pack defines the ordered production deployment sequence for RAFTOP CPAP CARE Pro."
W ""
W "This phase does not deploy automatically."
W "It defines the controlled execution path from pre-production readiness to production deployment."
W ""
W "------------------------------------------------------------"
W ""
W "CURRENT BASELINE"
W ""
W "- Phase 35 Master: READY"
W "- Patient Portal and myAir layer: READY"
W "- Patient APIs: READY"
W "- Patient Access Guard: READY"
W "- Advanced Security and Compliance: READY"
W "- Security Command Center: READY"
W "- Demo Operations: READY"
W "- Phase 36 Production Baseline: READY WITH WARNINGS"
W "- Phase 36.5 Production Readiness Summary: READY"
W "- Phase 37.1 Deployment Master Checklist: READY"
W "- Phase 37.2 Render Backend Deployment Guide: READY"
W "- Phase 37.3 Production PostgreSQL Setup Guide: READY"
W "- Phase 37.4 Frontend Deployment Guide: READY"
W "- Phase 37.5 Production Environment Checklist: READY"
W "- Phase 37.6 Production Smoke Test Script: READY"
W "- Phase 37.7 Go-Live Checklist: READY"
W ""
W "------------------------------------------------------------"
W ""
W "EXECUTION RULE"
W ""
W "Production deployment must follow the correct order."
W ""
W "The wrong order creates false success."
W ""
W "For example, deploying frontend before backend and database are stable creates a working-looking UI that fails under real use."
W ""
W "The correct order is:"
W ""
W "1. Freeze code"
W "2. Verify repository"
W "3. Provision production database"
W "4. Configure backend environment variables"
W "5. Deploy backend"
W "6. Verify backend health"
W "7. Deploy frontend"
W "8. Configure backend CORS against frontend URL"
W "9. Run production smoke test"
W "10. Bootstrap production tenant and admin"
W "11. Verify security and tenant isolation"
W "12. Verify backup and restore"
W "13. Make go or no-go decision"
W ""
W "------------------------------------------------------------"
W ""
W "STEP 1 - CODE FREEZE"
W ""
W "Required:"
W ""
W "- Stop adding new product features during deployment"
W "- Only allow deployment fixes"
W "- Confirm backend starts locally"
W "- Confirm frontend builds locally"
W "- Confirm tools scripts exist"
W "- Confirm reports directory exists"
W ""
W "Acceptance:"
W ""
W "- Code freeze approved: PENDING"
W "- Local backend preflight complete: PENDING"
W "- Local frontend preflight complete: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "STEP 2 - REPOSITORY VERIFICATION"
W ""
W "Required:"
W ""
W "- Latest code committed"
W "- Latest code pushed to GitHub"
W "- No real secrets in repository"
W "- No real .env.production file committed"
W "- enterprise-backend exists"
W "- enterprise-frontend exists"
W "- tools exists"
W "- reports exists"
W ""
W "Acceptance:"
W ""
W "- GitHub repository ready: PENDING"
W "- Secrets scan completed: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "STEP 3 - PRODUCTION DATABASE PROVISIONING"
W ""
W "Required:"
W ""
W "- Create production PostgreSQL database"
W "- Enable SSL connection"
W "- Obtain external DATABASE_URL"
W "- Confirm DATABASE_URL includes sslmode=require when applicable"
W "- Confirm database is not demo, staging, local, expired, or suspended"
W "- Define backup policy"
W "- Define restore test plan"
W ""
W "Acceptance:"
W ""
W "- Production database created: PENDING"
W "- SSL database URL ready: PENDING"
W "- Backup policy active: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "STEP 4 - BACKEND ENVIRONMENT CONFIGURATION"
W ""
W "Required backend env vars:"
W ""
W "- NODE_ENV=production"
W "- DATABASE_URL=production PostgreSQL SSL URL"
W "- JWT_SECRET=strong production secret"
W "- CORS_ORIGIN=temporary or final frontend URL"
W ""
W "Recommended backend env vars:"
W ""
W "- RESTORE_KEY=strong private key"
W "- SUPER_ADMIN_API_KEY=strong private key"
W "- DEMO_MODE=false"
W "- LOG_LEVEL=info"
W ""
W "Acceptance:"
W ""
W "- Backend env vars configured: PENDING"
W "- Weak JWT blocked: PENDING"
W "- No localhost database URL: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "STEP 5 - BACKEND DEPLOYMENT"
W ""
W "Render backend settings:"
W ""
W "- Service type: Web Service"
W "- Runtime: Node.js"
W "- Root directory: enterprise-backend"
W "- Build command: npm install"
W "- Start command: npm start"
W ""
W "Required after deployment:"
W ""
W "- Service starts"
W "- Logs show no crash"
W "- Database connection works"
W "- Health endpoint responds"
W ""
W "Acceptance:"
W ""
W "- Backend deployed: PENDING"
W "- Backend logs clean: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "STEP 6 - BACKEND HEALTH VERIFICATION"
W ""
W "Required check:"
W ""
W "GET /api/health"
W ""
W "Expected:"
W ""
W "- HTTP 200"
W "- JSON response"
W "- No 404"
W "- No 500"
W "- No proxy error"
W ""
W "Acceptance:"
W ""
W "- Backend health returns 200: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "STEP 7 - FRONTEND DEPLOYMENT"
W ""
W "Frontend hosting settings:"
W ""
W "- Service type: Static Site"
W "- Root directory: enterprise-frontend"
W "- Build command: npm install && npm run build"
W "- Publish directory: build for CRA or dist for Vite"
W ""
W "Required env var:"
W ""
W "- REACT_APP_API_BASE_URL or VITE_API_BASE_URL must point to production backend"
W ""
W "Acceptance:"
W ""
W "- Frontend deployed: PENDING"
W "- Frontend opens in browser: PENDING"
W "- Frontend does not call localhost: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "STEP 8 - CORS FINALIZATION"
W ""
W "After frontend deployment, set backend CORS_ORIGIN to final frontend URL."
W ""
W "Required:"
W ""
W "- CORS_ORIGIN equals production frontend URL"
W "- No wildcard CORS"
W "- No localhost CORS in production"
W ""
W "Acceptance:"
W ""
W "- CORS verified: PENDING"
W "- Frontend can call backend: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "STEP 9 - PRODUCTION SMOKE TEST"
W ""
W "Use the generated smoke test script:"
W ""
W ".\tools\run_phase37_production_smoke_test.ps1 -BackendUrl https://your-backend.onrender.com -TenantId raftopoulos-live"
W ""
W "Required checks:"
W ""
W "- Health endpoint returns 200"
W "- Auth login route exists"
W "- Tenant subscription route exists"
W "- Patients route exists"
W "- Devices route exists"
W "- ATLAS summary route exists"
W "- Required routes do not return 404"
W "- Required routes do not return 500"
W ""
W "Acceptance:"
W ""
W "- Production smoke test passed or ready with acceptable warnings: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "STEP 10 - PRODUCTION TENANT AND ADMIN BOOTSTRAP"
W ""
W "Required:"
W ""
W "- Create production tenant"
W "- Create first production admin"
W "- Do not use demo tenant as production tenant"
W "- Do not use weak admin password"
W "- Force password change if applicable"
W "- Log admin creation event"
W ""
W "Recommended first production tenant:"
W ""
W "- tenant_id: raftopoulos-live"
W "- tenant_name: RAFTOPOULOS"
W "- plan: enterprise"
W "- status: active"
W ""
W "Acceptance:"
W ""
W "- Production tenant created: PENDING"
W "- Production admin created: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "STEP 11 - SECURITY AND TENANT ISOLATION VERIFICATION"
W ""
W "Required:"
W ""
W "- Admin routes require admin role"
W "- Patient routes require patient access"
W "- Provider/staff roles are restricted"
W "- Tenant A cannot access Tenant B data"
W "- Failed login audit works"
W "- User activity audit works"
W "- Security Command Center loads"
W ""
W "Acceptance:"
W ""
W "- Role guards verified: PENDING"
W "- Tenant isolation verified: PENDING"
W "- Audit verification completed: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "STEP 12 - BACKUP AND RESTORE VERIFICATION"
W ""
W "Required:"
W ""
W "- Create backup"
W "- Restore backup into separate test or staging database"
W "- Verify login"
W "- Verify tenant records"
W "- Verify patients and devices"
W "- Verify ATLAS data"
W "- Verify audit logs"
W ""
W "Acceptance:"
W ""
W "- Backup created: PENDING"
W "- Restore test passed: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "STEP 13 - GO OR NO-GO DECISION"
W ""
W "GO is allowed only if:"
W ""
W "- Backend deployed"
W "- Frontend deployed"
W "- Production database active"
W "- SSL verified"
W "- Secrets protected"
W "- Smoke test passed"
W "- Tenant isolation verified"
W "- Backup and restore verified"
W "- Support owner assigned"
W "- Incident response process defined"
W ""
W "NO-GO if any critical gate is missing."
W ""
W "Acceptance:"
W ""
W "- Go or no-go decision recorded: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "EXECUTION CHECKLIST SUMMARY"
W ""
W "- Code freeze: PENDING"
W "- Repository verified: PENDING"
W "- Production database provisioned: PENDING"
W "- Backend env vars configured: PENDING"
W "- Backend deployed: PENDING"
W "- Backend health verified: PENDING"
W "- Frontend deployed: PENDING"
W "- CORS finalized: PENDING"
W "- Production smoke test executed: PENDING"
W "- Tenant bootstrap completed: PENDING"
W "- Admin bootstrap completed: PENDING"
W "- Security verified: PENDING"
W "- Tenant isolation verified: PENDING"
W "- Backup verified: PENDING"
W "- Restore verified: PENDING"
W "- Go or no-go decision recorded: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "NEXT PHASE"
W ""
W "Phase 38.2 - Production Preflight Verification Script"
W ""
W "This next phase should create a local verification script that checks whether the project has the required files, tools, deployment guides, smoke test script, and environment templates before actual deployment work begins."
W ""
W "------------------------------------------------------------"
W ""
W "FINAL VERDICT"
W ""
W "RAFTOP CPAP CARE Pro now has a production deployment execution pack."
W ""
W "The deployment sequence is defined, but production launch remains blocked until the execution gates are completed with real hosted infrastructure."
W ""
W "FINAL STATUS: PHASE38_PRODUCTION_DEPLOYMENT_EXECUTION_PACK_READY"

Write-Host ""
Write-Host "============================================================"
Write-Host "RAFTOP CPAP CARE Pro - Phase 38.1 Production Deployment Execution Pack"
Write-Host "============================================================"
Write-Host ""
Write-Host "Report created:"
Write-Host $ReportPath
Write-Host ""
Write-Host "FINAL STATUS: PHASE38_PRODUCTION_DEPLOYMENT_EXECUTION_PACK_READY"
Write-Host ""