# RAFTOP CPAP CARE Pro
# Phase 37.5 - Production Environment Checklist
# Safe ASCII-only script

$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$ReportsDir = Join-Path $Root "reports"

if (!(Test-Path $ReportsDir)) {
    New-Item -ItemType Directory -Path $ReportsDir | Out-Null
}

$Timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
$ReportPath = Join-Path $ReportsDir ("phase37_production_environment_checklist_" + $Timestamp + ".md")
$Now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

function W {
    param([string]$Text)
    Add-Content -Path $ReportPath -Value $Text -Encoding UTF8
}

Set-Content -Path $ReportPath -Value "# RAFTOP CPAP CARE Pro - Phase 37.5 Production Environment Checklist" -Encoding UTF8

W ""
W ("Generated: " + $Now)
W ""
W "FINAL STATUS"
W ""
W "FINAL STATUS: PHASE37_PRODUCTION_ENVIRONMENT_CHECKLIST_READY"
W ""
W "------------------------------------------------------------"
W ""
W "PURPOSE"
W ""
W "This checklist defines the production environment variable policy for RAFTOP CPAP CARE Pro."
W ""
W "This phase consolidates backend environment variables, frontend environment variables, database URL rules, secrets policy, CORS policy, and deployment validation."
W ""
W "------------------------------------------------------------"
W ""
W "CORE RULE"
W ""
W "Production configuration must be stored only in hosting provider environment variables."
W ""
W "Production secrets must never be committed to GitHub."
W ""
W "Production secrets must never be placed in frontend code."
W ""
W "------------------------------------------------------------"
W ""
W "BACKEND REQUIRED ENVIRONMENT VARIABLES"
W ""
W "- NODE_ENV=production"
W "- DATABASE_URL=production PostgreSQL URL with SSL"
W "- JWT_SECRET=strong private secret"
W "- CORS_ORIGIN=production frontend URL"
W ""
W "Recommended backend environment variables:"
W ""
W "- RESTORE_KEY=strong private restore key"
W "- SUPER_ADMIN_API_KEY=strong private super admin key"
W "- DEMO_MODE=false"
W "- LOG_LEVEL=info"
W ""
W "------------------------------------------------------------"
W ""
W "FRONTEND REQUIRED ENVIRONMENT VARIABLES"
W ""
W "The exact variable depends on the frontend build tool."
W ""
W "For Create React App:"
W ""
W "- REACT_APP_API_BASE_URL=https://production-backend-url"
W ""
W "For Vite:"
W ""
W "- VITE_API_BASE_URL=https://production-backend-url"
W ""
W "Only one production API base URL should be active."
W ""
W "The frontend must never contain secrets."
W ""
W "------------------------------------------------------------"
W ""
W "DATABASE_URL RULES"
W ""
W "Production DATABASE_URL must:"
W ""
W "- point to production PostgreSQL"
W "- use SSL"
W "- be stored only in backend hosting env vars"
W "- not point to localhost"
W "- not point to demo database"
W "- not point to staging database"
W "- not point to expired or suspended database"
W ""
W "Required format:"
W ""
W "postgresql://USER:PASSWORD@HOST:PORT/DATABASE?sslmode=require"
W ""
W "------------------------------------------------------------"
W ""
W "JWT_SECRET RULES"
W ""
W "JWT_SECRET must be:"
W ""
W "- strong"
W "- random"
W "- private"
W "- unique for production"
W "- different from development and demo"
W ""
W "Not allowed values:"
W ""
W "- secret"
W "- jwtsecret"
W "- password"
W "- admin"
W "- raftop"
W "- 123456"
W "- demo"
W "- development"
W ""
W "If strict JWT mode blocks startup, the production JWT_SECRET is missing or weak."
W ""
W "------------------------------------------------------------"
W ""
W "CORS RULES"
W ""
W "Backend CORS_ORIGIN must match the production frontend URL."
W ""
W "Example:"
W ""
W "CORS_ORIGIN=https://raftop-frontend.onrender.com"
W ""
W "Not allowed:"
W ""
W "- CORS_ORIGIN=*"
W "- CORS_ORIGIN=http://localhost:3001"
W "- CORS_ORIGIN=http://127.0.0.1:3001"
W "- missing CORS_ORIGIN in production"
W ""
W "Wildcard CORS is not acceptable for production."
W ""
W "------------------------------------------------------------"
W ""
W "ADMIN AND RESTORE KEY RULES"
W ""
W "SUPER_ADMIN_API_KEY and RESTORE_KEY must:"
W ""
W "- be strong"
W "- be private"
W "- be stored only in backend env vars"
W "- not appear in frontend code"
W "- not appear in reports"
W "- not appear in GitHub"
W "- not be shared in public messages"
W ""
W "These keys should be rotated if exposure is suspected."
W ""
W "------------------------------------------------------------"
W ""
W "DEMO VS PRODUCTION SEPARATION"
W ""
W "Production must be separate from demo in:"
W ""
W "- database"
W "- tenant data"
W "- user accounts"
W "- patient records"
W "- API base URL"
W "- frontend deployment"
W "- admin keys"
W "- JWT secret"
W "- import files"
W "- reports"
W ""
W "Demo tenant must not become the production tenant."
W ""
W "------------------------------------------------------------"
W ""
W "ENVIRONMENT FILE POLICY"
W ""
W "Allowed:"
W ""
W "- .env.example files"
W "- .env.production.example files"
W "- documentation without real secrets"
W ""
W "Not allowed:"
W ""
W "- real .env.production committed to GitHub"
W "- real DATABASE_URL committed to GitHub"
W "- real JWT_SECRET committed to GitHub"
W "- real admin keys committed to GitHub"
W "- frontend files containing backend secrets"
W ""
W "------------------------------------------------------------"
W ""
W "BACKEND ENVIRONMENT ACCEPTANCE CHECKLIST"
W ""
W "- NODE_ENV is production: PENDING"
W "- DATABASE_URL is production database: PENDING"
W "- DATABASE_URL uses SSL: PENDING"
W "- JWT_SECRET is strong: PENDING"
W "- CORS_ORIGIN matches production frontend: PENDING"
W "- RESTORE_KEY is strong: PENDING"
W "- SUPER_ADMIN_API_KEY is strong: PENDING"
W "- DEMO_MODE is false or controlled: PENDING"
W "- No localhost backend config: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "FRONTEND ENVIRONMENT ACCEPTANCE CHECKLIST"
W ""
W "- Production API base URL configured: PENDING"
W "- Frontend does not call localhost: PENDING"
W "- Frontend does not expose secrets: PENDING"
W "- Build succeeds: PENDING"
W "- Login flow reaches production backend: PENDING"
W "- Tenant context reaches production backend: PENDING"
W "- Patient portal reaches production backend: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "SECURITY ACCEPTANCE CHECKLIST"
W ""
W "- No real secrets in GitHub: PENDING"
W "- No real secrets in frontend: PENDING"
W "- JWT strict mode active: PENDING"
W "- Helmet active: PENDING"
W "- CORS restricted: PENDING"
W "- Admin keys protected: PENDING"
W "- Restore key protected: PENDING"
W "- Audit logging active: PENDING"
W "- Failed login audit active: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "DEPLOYMENT VALIDATION"
W ""
W "After setting production environment variables, validate:"
W ""
W "- backend starts successfully"
W "- health endpoint returns OK"
W "- database connection works"
W "- login route responds"
W "- protected routes return 401 or 403 when unauthenticated"
W "- frontend calls production backend"
W "- CORS does not block frontend"
W "- patient portal remains guarded"
W "- admin routes remain role-protected"
W ""
W "------------------------------------------------------------"
W ""
W "COMMON ENVIRONMENT FAILURES"
W ""
W "- Missing DATABASE_URL"
W "- Missing JWT_SECRET"
W "- Weak JWT_SECRET blocked by strict mode"
W "- DATABASE_URL points to localhost"
W "- DATABASE_URL points to old Render database"
W "- SSL/TLS required"
W "- CORS blocked"
W "- Frontend calls localhost in production"
W "- Backend starts but database connection fails"
W "- Secrets accidentally added to GitHub"
W ""
W "------------------------------------------------------------"
W ""
W "MINIMUM GO-LIVE REQUIREMENTS"
W ""
W "Before production go-live, the following must be true:"
W ""
W "- production backend env vars configured"
W "- production frontend env vars configured"
W "- production PostgreSQL configured"
W "- SSL database connection verified"
W "- frontend CORS verified"
W "- no secrets in GitHub"
W "- no secrets in frontend"
W "- demo and production data separated"
W "- smoke test script passes"
W ""
W "------------------------------------------------------------"
W ""
W "NEXT PHASE"
W ""
W "Phase 37.6 - Production Smoke Test Script"
W ""
W "This will create a script that checks backend health, route availability, protected route behavior, environment readiness, and production endpoint responses."
W ""
W "------------------------------------------------------------"
W ""
W "FINAL VERDICT"
W ""
W "RAFTOP CPAP CARE Pro now has a production environment checklist."
W ""
W "The system must not go live until production environment variables, database URL, JWT secret, CORS, frontend API URL, and secrets policy are verified."
W ""
W "FINAL STATUS: PHASE37_PRODUCTION_ENVIRONMENT_CHECKLIST_READY"

Write-Host ""
Write-Host "============================================================"
Write-Host "RAFTOP CPAP CARE Pro - Phase 37.5 Production Environment Checklist"
Write-Host "============================================================"
Write-Host ""
Write-Host "Report created:"
Write-Host $ReportPath
Write-Host ""
Write-Host "FINAL STATUS: PHASE37_PRODUCTION_ENVIRONMENT_CHECKLIST_READY"
Write-Host ""