# RAFTOP CPAP CARE Pro
# Phase 37.3 - Production PostgreSQL Setup Guide
# Safe ASCII-only script

$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$ReportsDir = Join-Path $Root "reports"

if (!(Test-Path $ReportsDir)) {
    New-Item -ItemType Directory -Path $ReportsDir | Out-Null
}

$Timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
$ReportPath = Join-Path $ReportsDir ("phase37_production_postgresql_setup_guide_" + $Timestamp + ".md")
$Now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

function W {
    param([string]$Text)
    Add-Content -Path $ReportPath -Value $Text -Encoding UTF8
}

Set-Content -Path $ReportPath -Value "# RAFTOP CPAP CARE Pro - Phase 37.3 Production PostgreSQL Setup Guide" -Encoding UTF8

W ""
W ("Generated: " + $Now)
W ""
W "FINAL STATUS"
W ""
W "FINAL STATUS: PHASE37_PRODUCTION_POSTGRESQL_SETUP_GUIDE_READY"
W ""
W "------------------------------------------------------------"
W ""
W "PURPOSE"
W ""
W "This guide defines the production PostgreSQL preparation plan for RAFTOP CPAP CARE Pro."
W ""
W "This phase does not create the database automatically."
W "It defines the production database rules before live deployment."
W ""
W "------------------------------------------------------------"
W ""
W "CORE RULE"
W ""
W "The production database must be separate from development, demo, test, expired, suspended, or debugging databases."
W ""
W "Real patient data must never be stored in a demo or test database."
W ""
W "------------------------------------------------------------"
W ""
W "REQUIRED INFRASTRUCTURE"
W ""
W "- Database Engine: PostgreSQL"
W "- Hosting: Render PostgreSQL, Neon, Supabase, or another production-grade PostgreSQL provider"
W "- SSL: Required"
W "- Backups: Required"
W "- Restore Test: Required before go-live"
W "- Demo and Production Separation: Required"
W "- Access Control: Restricted"
W "- Connection String: Stored only in hosted environment variables"
W ""
W "------------------------------------------------------------"
W ""
W "PRODUCTION DATABASE_URL"
W ""
W "Required format:"
W ""
W "postgresql://USER:PASSWORD@HOST:PORT/DATABASE?sslmode=require"
W ""
W "Not allowed:"
W ""
W "- localhost"
W "- 127.0.0.1"
W "- demo database"
W "- test database"
W "- expired database"
W "- suspended Render database"
W ""
W "------------------------------------------------------------"
W ""
W "RECOMMENDED ENVIRONMENT STRUCTURE"
W ""
W "- Development database: raftop_dev"
W "- Demo database: raftop_demo"
W "- Staging database: raftop_staging"
W "- Production database: raftop_production"
W ""
W "------------------------------------------------------------"
W ""
W "REQUIRED DATA MODULES"
W ""
W "- users"
W "- tenants"
W "- patients"
W "- devices"
W "- compliance records"
W "- tasks"
W "- notes"
W "- referrals"
W "- notifications"
W "- subscriptions"
W "- atlas signals"
W "- atlas actions"
W "- audit logs"
W "- failed login logs"
W "- patient access records"
W "- security events"
W ""
W "------------------------------------------------------------"
W ""
W "BACKUP POLICY"
W ""
W "- Automated database backup: daily"
W "- Manual backup before major updates: required"
W "- Backup retention: at least 7 days"
W "- Restore test: required before go-live and after major schema changes"
W ""
W "A backup is not enough. Restore must be tested."
W ""
W "------------------------------------------------------------"
W ""
W "RESTORE TEST"
W ""
W "Minimum restore test:"
W ""
W "1. Create backup."
W "2. Restore into a separate test or staging database."
W "3. Verify core tables."
W "4. Verify login."
W "5. Verify tenant."
W "6. Verify patients and devices."
W "7. Verify ATLAS."
W "8. Verify audit logs."
W ""
W "If restore was not tested, backup is only a hope."
W ""
W "------------------------------------------------------------"
W ""
W "MIGRATION AND SEED STRATEGY"
W ""
W "- Schema creation: SQL migrations or controlled bootstrap"
W "- Initial admin user: bootstrap script"
W "- Initial tenant: bootstrap script"
W "- Demo data: not inside production database"
W "- Patient import: controlled CSV import flow"
W "- Rollback: backup before migration"
W "- Schema changes: versioned migration plan only"
W ""
W "------------------------------------------------------------"
W ""
W "ADMIN BOOTSTRAP"
W ""
W "The production database must have a controlled initial admin."
W ""
W "Requirements:"
W ""
W "- no hardcoded password"
W "- no admin123 password"
W "- no public password sharing"
W "- mandatory password change after first login"
W "- audit event for admin creation"
W ""
W "------------------------------------------------------------"
W ""
W "TENANT BOOTSTRAP"
W ""
W "First production tenant requirements:"
W ""
W "- tenant_id: raftopoulos-live"
W "- tenant_name: RAFTOPOULOS"
W "- plan: enterprise"
W "- status: active"
W "- patient_limit: real commercial limit"
W "- seats: real user count"
W "- modules: patient portal, atlas, compliance, security"
W ""
W "The demo tenant must not become the production tenant."
W ""
W "------------------------------------------------------------"
W ""
W "PATIENT DATA IMPORT RULES"
W ""
W "Before importing real patient data:"
W ""
W "1. Assign import owner."
W "2. Use a fixed CSV format."
W "3. Validate before import."
W "4. Reject incomplete records."
W "5. Write audit event."
W "6. Take backup before import."
W "7. Run sample verification after import."
W ""
W "------------------------------------------------------------"
W ""
W "SSL RULES"
W ""
W "Backend to database connection must use SSL."
W ""
W "Required DATABASE_URL suffix:"
W ""
W "?sslmode=require"
W ""
W "If SSL/TLS required appears, the DATABASE_URL or backend SSL configuration is wrong."
W ""
W "------------------------------------------------------------"
W ""
W "ACCESS CONTROL"
W ""
W "Production database access must be limited to:"
W ""
W "- backend service"
W "- authorized admin or devops operator"
W "- backup and restore process"
W ""
W "Frontend, demo users, public scripts, and unrelated partners must not access the database directly."
W ""
W "------------------------------------------------------------"
W ""
W "ACCEPTANCE CHECKLIST"
W ""
W "- Production database created: PENDING"
W "- SSL DATABASE_URL available: PENDING"
W "- DATABASE_URL stored only in Render env vars: PENDING"
W "- Development and demo databases separated: PENDING"
W "- Backup policy selected: PENDING"
W "- Restore test completed: PENDING"
W "- Admin bootstrap defined: PENDING"
W "- Tenant bootstrap defined: PENDING"
W "- Migration strategy defined: PENDING"
W "- Patient import policy defined: PENDING"
W "- Audit and security tables verified: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "CRITICAL RISKS"
W ""
W "- Demo database used as production: Critical"
W "- No SSL: Critical"
W "- No backup: Critical"
W "- No restore test: High"
W "- Demo data inside production: High"
W "- Weak admin bootstrap: High"
W "- Tenant mix-up: Critical"
W "- Patient import without validation: Critical"
W ""
W "------------------------------------------------------------"
W ""
W "NEXT PHASE"
W ""
W "Phase 37.4 - Frontend Deployment Guide"
W ""
W "This will define frontend deployment, production backend connection, login verification, tenant context verification, patient portal verification, and admin route verification."
W ""
W "------------------------------------------------------------"
W ""
W "FINAL VERDICT"
W ""
W "RAFTOP CPAP CARE Pro now has a production PostgreSQL setup guide."
W ""
W "The platform must not go live until production database, SSL, backups, restore test, admin bootstrap, tenant bootstrap, and migration strategy are completed."
W ""
W "FINAL STATUS: PHASE37_PRODUCTION_POSTGRESQL_SETUP_GUIDE_READY"

Write-Host ""
Write-Host "============================================================"
Write-Host "RAFTOP CPAP CARE Pro - Phase 37.3 Production PostgreSQL Setup Guide"
Write-Host "============================================================"
Write-Host ""
Write-Host "Report created:"
Write-Host $ReportPath
Write-Host ""
Write-Host "FINAL STATUS: PHASE37_PRODUCTION_POSTGRESQL_SETUP_GUIDE_READY"
Write-Host ""