# RAFTOP CPAP CARE Pro
# Phase 37.7 - Production Go-Live Checklist
# Safe ASCII-only script

$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$ReportsDir = Join-Path $Root "reports"

if (!(Test-Path $ReportsDir)) {
    New-Item -ItemType Directory -Path $ReportsDir | Out-Null
}

$Timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
$ReportPath = Join-Path $ReportsDir ("phase37_go_live_checklist_" + $Timestamp + ".md")
$Now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

function W {
    param([string]$Text)
    Add-Content -Path $ReportPath -Value $Text -Encoding UTF8
}

Set-Content -Path $ReportPath -Value "# RAFTOP CPAP CARE Pro - Phase 37.7 Production Go-Live Checklist" -Encoding UTF8

W ""
W ("Generated: " + $Now)
W ""
W "FINAL STATUS"
W ""
W "FINAL STATUS: PHASE37_GO_LIVE_CHECKLIST_READY"
W ""
W "------------------------------------------------------------"
W ""
W "PURPOSE"
W ""
W "This checklist defines the minimum go-live requirements for RAFTOP CPAP CARE Pro."
W ""
W "This document does not approve production launch by itself."
W "It defines the gates that must be passed before real customers, real providers, or real patient data are onboarded."
W ""
W "------------------------------------------------------------"
W ""
W "CURRENT BASELINE"
W ""
W "- Phase 35 Master: READY"
W "- Patient Portal and myAir layer: READY"
W "- Patient APIs: READY"
W "- Patient Access Guard: READY"
W "- Advanced Security and Compliance: READY"
W "- User Activity Audit: READY"
W "- Failed Login Audit: READY"
W "- Security Command Center: READY"
W "- Pre-demo check: READY"
W "- Evidence report generator: READY"
W "- Demo launcher: READY"
W "- Demo operations verification: READY"
W "- Phase 36 production baseline: READY WITH WARNINGS"
W "- Phase 36.5 production readiness summary: READY"
W "- Phase 37.1 deployment master checklist: READY"
W "- Phase 37.2 Render backend deployment guide: READY"
W "- Phase 37.3 production PostgreSQL setup guide: READY"
W "- Phase 37.4 frontend deployment guide: READY"
W "- Phase 37.5 production environment checklist: READY"
W "- Phase 37.6 production smoke test script: READY"
W ""
W "------------------------------------------------------------"
W ""
W "GO-LIVE RULE"
W ""
W "RAFTOP CPAP CARE Pro must not go live until all critical gates are passed."
W ""
W "A demo-ready system is not the same as a production-ready system."
W ""
W "Production readiness requires hosted infrastructure, production database, SSL, secrets policy, backups, restore validation, smoke tests, access control verification, and operational support."
W ""
W "------------------------------------------------------------"
W ""
W "CRITICAL GO-LIVE BLOCKERS"
W ""
W "The system is blocked from production if any of the following are true:"
W ""
W "- Production backend is not deployed"
W "- Production frontend is not deployed"
W "- Production PostgreSQL database is missing"
W "- DATABASE_URL points to localhost, demo, staging, expired, or suspended database"
W "- SSL database connection is not verified"
W "- JWT_SECRET is missing or weak"
W "- CORS_ORIGIN is wildcard or wrong"
W "- Frontend calls localhost"
W "- Real secrets exist in GitHub"
W "- Real secrets exist in frontend code"
W "- Backup policy is missing"
W "- Restore test has not been completed"
W "- Tenant isolation has not been verified"
W "- Patient access guard has not been verified"
W "- Admin routes are accessible to non-admin roles"
W "- Patient portal is accessible without proper guard"
W "- Production smoke test has not passed"
W "- Demo data is mixed with production data"
W "- No incident response process exists"
W ""
W "------------------------------------------------------------"
W ""
W "BACKEND GO-LIVE GATE"
W ""
W "Required:"
W ""
W "- Backend deployed to production hosting"
W "- NODE_ENV is production"
W "- Health endpoint returns 200"
W "- Auth route exists"
W "- Protected tenant routes respond with 401 or 403 when unauthenticated"
W "- Backend connects to production database"
W "- Helmet is active"
W "- Strict JWT mode is active"
W "- Logs show no startup crash"
W "- No critical 500 errors during smoke test"
W ""
W "Status: PENDING UNTIL LIVE DEPLOYMENT"
W ""
W "------------------------------------------------------------"
W ""
W "DATABASE GO-LIVE GATE"
W ""
W "Required:"
W ""
W "- Production PostgreSQL database exists"
W "- SSL DATABASE_URL is configured"
W "- DATABASE_URL is stored only in backend hosting environment variables"
W "- Development, demo, staging, and production databases are separate"
W "- Backup policy is active"
W "- Restore test completed"
W "- Admin bootstrap defined"
W "- Tenant bootstrap defined"
W "- Migration strategy defined"
W "- Patient import policy defined"
W "- Audit and security tables verified"
W ""
W "Status: PENDING UNTIL PRODUCTION DATABASE EXISTS"
W ""
W "------------------------------------------------------------"
W ""
W "FRONTEND GO-LIVE GATE"
W ""
W "Required:"
W ""
W "- Frontend deployed to production hosting"
W "- Production API base URL is configured"
W "- Frontend does not call localhost"
W "- Login page loads"
W "- Admin dashboard loads after login"
W "- Tenant context works"
W "- Patient pages load"
W "- Device pages load"
W "- ATLAS pages load"
W "- Security Command Center loads"
W "- Patient portal routes load"
W "- Direct route refresh works"
W "- No blank white screen"
W "- No exposed frontend secrets"
W ""
W "Status: PENDING UNTIL LIVE FRONTEND DEPLOYMENT"
W ""
W "------------------------------------------------------------"
W ""
W "SECURITY GO-LIVE GATE"
W ""
W "Required:"
W ""
W "- No production secrets in GitHub"
W "- No production secrets in frontend code"
W "- JWT_SECRET strong and private"
W "- SUPER_ADMIN_API_KEY strong and private"
W "- RESTORE_KEY strong and private"
W "- CORS restricted to production frontend"
W "- Failed login audit active"
W "- User activity audit active"
W "- Patient access guard active"
W "- Role-based route protection verified"
W "- Tenant isolation verified"
W "- Super admin access controlled"
W ""
W "Status: PENDING UNTIL SECURITY VERIFICATION"
W ""
W "------------------------------------------------------------"
W ""
W "TENANT GO-LIVE GATE"
W ""
W "Required:"
W ""
W "- Production tenant created"
W "- Demo tenant is not used as production tenant"
W "- Tenant plan configured"
W "- Tenant status active"
W "- Patient limit configured"
W "- Seat count configured"
W "- Modules configured"
W "- Provider/admin users assigned"
W "- Tenant isolation test passed"
W ""
W "Recommended first production tenant:"
W ""
W "- tenant_id: raftopoulos-live"
W "- tenant_name: RAFTOPOULOS"
W "- plan: enterprise"
W "- status: active"
W ""
W "Status: PENDING UNTIL TENANT BOOTSTRAP"
W ""
W "------------------------------------------------------------"
W ""
W "PATIENT DATA GO-LIVE GATE"
W ""
W "Required before importing real patient data:"
W ""
W "- Import owner assigned"
W "- CSV format locked"
W "- Validation rules defined"
W "- Backup taken before import"
W "- Audit event created for import"
W "- Sample verification completed after import"
W "- Failed imports handled safely"
W "- No patient data imported into demo database"
W ""
W "Status: PENDING UNTIL PATIENT IMPORT POLICY IS EXECUTED"
W ""
W "------------------------------------------------------------"
W ""
W "OPERATIONAL GO-LIVE GATE"
W ""
W "Required:"
W ""
W "- Support owner assigned"
W "- Incident response process defined"
W "- Backup owner assigned"
W "- Restore process documented"
W "- Admin access policy defined"
W "- Tenant onboarding process defined"
W "- Provider onboarding process defined"
W "- Patient support process defined"
W "- Monitoring approach selected"
W "- Error escalation process defined"
W ""
W "Status: PENDING UNTIL OPERATIONS OWNER IS ASSIGNED"
W ""
W "------------------------------------------------------------"
W ""
W "COMMERCIAL GO-LIVE GATE"
W ""
W "Required:"
W ""
W "- Commercial offer defined"
W "- Pilot agreement or client approval defined"
W "- Pricing model defined"
W "- Billing/subscription rules defined"
W "- Demo vs production boundary explained to client"
W "- Provider onboarding material ready"
W "- Admin training checklist ready"
W "- Patient communication process ready"
W ""
W "Status: PENDING UNTIL COMMERCIAL LAUNCH PACKAGE"
W ""
W "------------------------------------------------------------"
W ""
W "MINIMUM SMOKE TEST REQUIREMENTS"
W ""
W "The production smoke test must verify:"
W ""
W "- GET /api/health returns 200"
W "- POST /api/auth/login route exists"
W "- GET /api/tenant/subscription/status route exists"
W "- GET /api/tenant/patients route exists"
W "- GET /api/tenant/devices route exists"
W "- GET /api/tenant/atlas/summary route exists"
W "- Protected routes return acceptable protected responses"
W "- Required routes do not return 404"
W "- Required routes do not return 500"
W ""
W "Smoke test command example:"
W ""
W ".\tools\run_phase37_production_smoke_test.ps1 -BackendUrl https://your-backend.onrender.com -TenantId raftopoulos-live"
W ""
W "Status: PENDING UNTIL PRODUCTION BACKEND EXISTS"
W ""
W "------------------------------------------------------------"
W ""
W "GO-LIVE DECISION MATRIX"
W ""
W "APPROVED FOR DEMO:"
W "- Allowed when demo checks pass and no production patient data is used."
W ""
W "APPROVED FOR STAGING:"
W "- Allowed when backend, frontend, database, and smoke tests work with staging data."
W ""
W "APPROVED FOR CONTROLLED PILOT:"
W "- Allowed only after production infrastructure, access controls, backups, restore test, and tenant isolation are verified."
W ""
W "APPROVED FOR FULL PRODUCTION:"
W "- Allowed only after all critical gates are passed and operational support is active."
W ""
W "------------------------------------------------------------"
W ""
W "FINAL GO-LIVE CHECKLIST"
W ""
W "- Production backend deployed: PENDING"
W "- Production frontend deployed: PENDING"
W "- Production database created: PENDING"
W "- SSL database connection verified: PENDING"
W "- Production env vars configured: PENDING"
W "- No secrets in GitHub: PENDING"
W "- No secrets in frontend: PENDING"
W "- CORS restricted: PENDING"
W "- JWT strict mode verified: PENDING"
W "- Production smoke test passed: PENDING"
W "- Backup policy active: PENDING"
W "- Restore test completed: PENDING"
W "- Tenant bootstrap completed: PENDING"
W "- Tenant isolation verified: PENDING"
W "- Admin bootstrap completed: PENDING"
W "- Role guards verified: PENDING"
W "- Patient access guard verified: PENDING"
W "- Patient import policy approved: PENDING"
W "- Monitoring approach selected: PENDING"
W "- Incident response process defined: PENDING"
W "- Support owner assigned: PENDING"
W "- Commercial launch package approved: PENDING"
W ""
W "------------------------------------------------------------"
W ""
W "NEXT PHASE"
W ""
W "Phase 38 - Production Deployment Execution Pack"
W ""
W "This next phase should prepare the actual deployment execution sequence: backend deployment, database provisioning, frontend deployment, production env setup, smoke test execution, and go-live decision report."
W ""
W "------------------------------------------------------------"
W ""
W "FINAL VERDICT"
W ""
W "RAFTOP CPAP CARE Pro now has a production go-live checklist."
W ""
W "The system remains demo and pre-production ready, but full production launch requires all critical go-live gates to be passed."
W ""
W "FINAL STATUS: PHASE37_GO_LIVE_CHECKLIST_READY"

Write-Host ""
Write-Host "============================================================"
Write-Host "RAFTOP CPAP CARE Pro - Phase 37.7 Production Go-Live Checklist"
Write-Host "============================================================"
Write-Host ""
Write-Host "Report created:"
Write-Host $ReportPath
Write-Host ""
Write-Host "FINAL STATUS: PHASE37_GO_LIVE_CHECKLIST_READY"
Write-Host ""